os: Visual Studio 2015

platform: x64

install:
  - '"C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd" /x64'
  - choco install strawberryperl
  - SET PATH=C:\strawberry\c\bin;C:\strawberry\perl\site\bin;C:\strawberry\perl\bin;%PATH%
  - ps: (new-object net.webclient).DownloadFile('http://rakudo.org/downloads/star/rakudo-star-2016.04-x86_64 (JIT).msi', 'rakudo.msi')
  - ps: msiexec /i rakudo.msi /qn /norestart /log install.log
  - type install.log
  - dir C:\rakudo\bin
  - SET PATH=C:\rakudo\bin;C:\rakudo\share\perl6\site\bin;%PATH%
  - echo %PATH%
  - panda installdeps .

build: off

test_script:
  - prove -v -e "perl6 -Ilib" t/

shallow_clone: true
